version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moneycat
    ports:
    - 127.0.0.1:8000:80
    volumes:
    - ./configs:/etc/moneycat
    command: ["-f", "/etc/moneycat/local.yml"]
    depends_on:
      - "postgres"
      - "redis"
    restart: on-failure

  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: NeverGonnaGiveYouUp
      POSTGRES_DB: moneycat
    volumes:
      - ./backup.sql:/backup.sql

  redis:
    image: redis
    restart: on-failure
    volumes:
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
