version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    #image: softree/moneycat:master
    container_name: moneycat
    ports:
    - 9000:80
    volumes:
    - ./configs:/etc/moneycat
    command: ["-f", "/etc/moneycat/local.yml"]
    restart: on-failure

  db:
    image: postgres:latest
    restart: on-failure
    volumes:
    - /postgres-data:/var/lib/postgresql/data/

  redis:
    image: redis
    restart: on-failure
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - ./configs/redis.conf:/usr/local/etc/redis/redis.conf
