version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moneycat
    ports:
    - 9000:80
    volumes:
    - ./configs:/etc/moneycat
    command: ["-f", "/etc/moneycat/local.yml"]
    restart: on-failure

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 'this_is_secret'
      POSTGRES_DB: moneycat
    volumes:
      - 'postgres-data:/var/lib/postgresql/data/'

volumes:
  postgres-data:
