version: "3.8"
services:
  api:
    build: .
    image: moneycat:dev
    ports:
    - 127.0.0.1:8000:80
    volumes:
    - ./config.yml:/etc/moneycat/moneycat.yml
    command: ["-c", "/etc/moneycat/moneycat.yml"]
    depends_on:
      - "postgres"
      - "redis"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: NeverGonnaGiveYouUp
      POSTGRES_DB: moneycat
    volumes:
      - ./backup.sql:/backup.sql

  redis:
    image: redis:alpine
