version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    #image: softree/moneycat:master
    container_name: moneycat
    ports:
    - 9000:80
    volumes:
    - ./configs:/etc/moneycat
    command: ["-f", "/etc/moneycat/local.yml"]
    restart: on-failure
