---

ip: 0.0.0.0
port: 80
domain: 'localhost'
secure: False
logLevel: 'Debug'

postgres_user: 'user'
postgres_password: 'NeverGonnaGiveYouUp'
postgres_host: 'postgres'
postgres_db: 'moneycat'

redis_session_path: 'redis://user:@redis:6379/1'
redis_currency_path: 'redis://user:@redis:6379/2'
