// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  entity

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Currencies ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Currencies ) UnmarshalJSON([]byte) error { return nil }
func ( Currencies ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Currencies ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Currencies *Currencies

func ( Currency ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Currency ) UnmarshalJSON([]byte) error { return nil }
func ( Currency ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Currency ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Currency *Currency
