// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  entity

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Payment ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Payment ) UnmarshalJSON([]byte) error { return nil }
func ( Payment ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Payment ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Payment *Payment

func ( Payments ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Payments ) UnmarshalJSON([]byte) error { return nil }
func ( Payments ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Payments ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Payments *Payments
