name: Docker

on: workflow_dispatch

jobs:
  push_canal:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out code into the Go module directory
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push canal
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./canal/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: softree/canal:latest
      -
        name: Canal digest
        run: echo canal ${{ steps.docker_build.outputs.digest }}

  push_authorization:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out code into the Go module directory
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push authorization
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./authorization/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: softree/authorization:latest
      -
        name: Authorization digest
        run: echo authorization ${{ steps.docker_build.outputs.digest }}

  push_currency:
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out code into the Go module directory
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Push currency
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./currency/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: softree/currency:latest
    -
      name: Currency digest
      run: echo currency ${{ steps.docker_build.outputs.digest }}

  push_profile:
    runs-on: ubuntu-latest
    steps:
    -
      name: Check out code into the Go module directory
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Push profile
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./profile/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: softree/profile:latest
    -
      name: Profile digest
      run: echo profile ${{ steps.docker_build.outputs.digest }}
